name: CI Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14.0]
    steps:
      - name: Nodejs Setup
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Circom
        run: |
          wget https://github.com/iden3/circom/releases/latest/download/circom-linux-amd64 &&
          sudo mv ./circom-linux-amd64 /usr/bin/circom &&
          sudo chmod +x /usr/bin/circom
      - name: Library Build
        run: yarn && yarn build
      - name: Library Test
        run: yarn compile && yarn preprocess && yarn ptau && yarn setup && yarn test
