name: CI Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14.0]
    steps:
      - name: Nodejs Setup
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Library Build
        run: yarn && yarn build
        env:
          CI: true
      - name: Library Test
        run: yarn && yarn compile && yarn ptau && yarn setup && yarn test
        env:
          CI: true
